[website]
"e-mail"     = "https://mail.google.com/mail/ca/u/0/#inbox"
"math fly"   = "mathfly.org"
"what's app" = "https://web.whatsapp.com/"
"amazon"       = "https://smile.amazon.co.uk/ref=nav_logo"
"calendar"     = "https://www.google.com/calendar"
"facebook"     = "facebook.com"
"iPlayer"      = "https://www.bbc.co.uk/iplayer"
"kindle"       = "https://smile.amazon.co.uk/Kindle-eBooks-books/b/ref=nav_shopall_kbo5?ie=UTF8&node=341689031"
"maps"         = "https://www.google.com/maps"
"scholar"      = "scholar.google.co.uk"
"SMS"          = "https://mightytext.net/web8/"
"spectator"    = "spectator.co.uk"
"times"        = "thetimes.co.uk"
"twitter"      = "twitter.com/home"
"youtube"      = "youtube.com"

[folder]
summer = "C:\\Users\\Mike\\Documents\\summer of stats"
mike = "C:\\Users\\Mike"
"app data" = "C:\\Users\\Mike\\AppData"
"math fly" = "C:\\Users\\Mike\\Documents\\NatLink\\mathfly"
downloads = "C:\\Users\\Mike\\Downloads"
"git hub" = "C:\\Users\\Mike\\Documents\\GitHub"
"saved images" = "C:\\Users\\Mike\\Pictures\\saved"
"queue tea" = "C:\\Users\\Mike\\Pictures\\pol\\qt"
documents = "C:\\Users\\Mike\\Documents"
sea = "C:\\"
papers = "C:\\Users\\Mike\\Documents\\papers"
films = "E:\\films"
pictures = "C:\\Users\\Mike\\Pictures"
caster = "C:\\Users\\Mike\\Documents\\NatLink\\caster"
e-books = "C:\\Users\\Mike\\Documents\\ebooks"

[program]
spotify = "C:\\Users\\Mike\\AppData\\Roaming\\Spotify\\Spotify.exe"
licks = "C:\\Program Files (x86)\\LyX 2.3\\bin\\LyX.exe"
"scientific notebook" = "C:\\Program Files (x86)\\Scientific Notebook\\scinoteb.exe"
chrome = "C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe"
"our studio" = "C:\\Program Files\\RStudio\\bin\\rstudio.exe"
Kindle = "C:\\Users\\Mike\\AppData\\Local\\Amazon\\Kindle\\application\\Kindle.exe"
torrent = "C:\\Program Files (x86)\\uTorrent\\uTorrent.exe"
sublime = "C:\\Program Files\\Sublime Text 3\\sublime_text.exe"

[file]
