pronunciation = "C"
title_contexts = [".c", ".h"]
function_prefix = "fun"
template_prefix = "template"

[functions]
"free" = "free"
"mallock" = "malloc"
"mem copy" = "memcpy"
"print" = "printf"
"size of" = "sizeof"
"stir length" = "strlen"
"stir copy" = "strcpy"
"ops lock create" = "lock_create"
"ops lock destroy" = "lock_destroy"
"ops lock release" = "lock_release"
"ops lock acquire" = "lock_acquire"
"ops C V create" = "cv_create"
"ops C V destroy" = "cv_destroy"
"ops C V signal" = "cv_signal"
"ops C V broadcast" = "cv_broadcast"
"ops semaphore create" = "sem_create"
"ops semaphore destroy" = "sem_destroy"
"ops semaphore increment" = "V"
"ops semaphore decrement" = "P"

[commands]
"assign" = " = "
"for loop" = ["for (i=0; i<; i++) {}", "left enter"]
"iffae" = ["if () {}", "left enter"]
"hash include" = ["#include <>", "left"]
"hash define" = "#define "
"lodge and" = " && "
"lodge or" = " || "
"shells" = ["else {}", "left enter"]
"structure" = ["struct  {};", "left:2, enter, up, end, left:2"]
"semi" = ["", "end end ;"]
"type def struct" = ["typedef struct {} ;", "left:3, enter, down, end, left:2"]
"return" = ["return ;", "left"]
"value false" = "false"
"value true" = "true"
"value null" = "NULL"
"while loop" = ["while () {}", "left, enter, up, end, left:3"]

[types]
"boolean" = "bool"
"inter" = "int"
"unsigned" = "unsigned"
"void" = "void"
"struct" = "struct "
"enum" = "enum "
"ops lock" ="struct lock *"
"ops C V" = "struct cv *"
"ops semaphore" = "struct semaphore *"

[templates]
