"pronunciation"   = "Markdown"
"title_contexts"  = [".md", ".Rmd", "Gitter", "Notepad", ".html", "· issue #", "· pull request #"]
"insert_prefix"   = "insert"
"template_prefix" = "template"
"output_prefix"   = "output"
"option_prefix"   = "option"

[elements]
"list"                    = "* "
"numbered list"           = "1. "
"block quote"           = "> "
"image"                   = ["![]()", "left left left"]
"in-line code"            = ["``", "left"]
"code block" = ["``````", "left left left enter enter up"]
"horizontal rule"         = "---"
"heading"                 = "# "
"subheading"              = "## "
"sub sub heading"         = "### "
"reference"               = ["[@]", "left"]
"italics" = ["__", "left"]
"bold text"             = ["****", "left left"]

[alternating]
# "link"                  = ["[](url)", "left:6"]
"hidden R code"         = ["", "backtick:3", "{r, include=FALSE}", "enter:2, backtick:3, up"]
"graph"                 = ["", "backtick:3", "{r echo=FALSE}", "enter:2, backtick:3, up"]
"header"                = ["", "c-home", "---\n\n---", "up", "fontsize: 12pt"]

[outputs]
"beamer [presentation]" = "output:\nbeamer_presentation:\ndf_print: kable\ntheme: metropolis"
"HTML"                  = "output: html_document"
"PDF"                   = "output:\npdf_document:\ndf_print: kable"
"word"                  = "output:\nword_document"

[options]
"author"            = "author: "
"bibliography"      = "bibliography: "
"date"              = "date: "
"figure width"      = "fig_width: "
"figure height"     = "fig_height: "
"figure caption"    = "fig_caption: true"
"font size"         = "fontsize: 11pt"
"keep tex"          = "keep_tex: true"
"small output"      = "header-includes:\n- \\let\\oldverbatim\\verbatim\n- \\def\\verbatim{\\tiny \\oldverbatim}"
"table of contents" = "toc: true"
"title"             = "title: "

[languages]
"python" = "python"
"are" = "r"

[remarks]
"left column" = [".left-column[]", "left, enter:2, up"]
"right column" = [".right-column[]", "left, enter:2, up"]
"columns" = [".left-column[]", "left, enter:2, end, enter", ".right-column[]", "left, enter:2, up:4"]
"footnote" = [".footnote[.red[*] ]", "left"]

[templates]
"remark" = '''
<!DOCTYPE html>
<html>
  <head>
    <title>Presentation</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <style type="text/css">
      @import url(https://fonts.googleapis.com/css?family=Yanone+Kaffeesatz);
      @import url(https://fonts.googleapis.com/css?family=Droid+Serif:400,700,400italic);
      @import url(https://fonts.googleapis.com/css?family=Ubuntu+Mono:400,700,400italic);

      body { font-family: 'Droid Serif'; }
      h1, h2, h3 {
        font-family: 'Yanone Kaffeesatz';
        font-weight: normal;
      }
      .remark-code, .remark-inline-code { font-family: 'Ubuntu Mono'; }
      .remark-slide-content h1 { font-size: 3em; }
      .remark-slide-content h2 { font-size: 2em; }
      .remark-slide-content h3 { font-size: 1.6em; }
      .footnote {
        position: absolute;
        bottom: 3em;
      }
      li p { line-height: 1.25em; }
      .red { color: #fa0000; }
      .large { font-size: 2em; }
      a, a > code {
        color: rgb(249, 38, 114);
        text-decoration: none;
      }
      code {
        background: #e7e8e2;
        border-radius: 5px;
      }
      .remark-code-line-highlighted     { background-color: #ffffff; }
      .pull-left {
        float: left;
        width: 47%;
      }
      .pull-right {
        float: right;
        width: 47%;
      }
      .pull-right ~ p {
        clear: both;
      }
      #slideshow .slide .content code {
        font-size: 0.8em;
      }
      #slideshow .slide .content pre code {
        font-size: 0.9em;
        padding: 15px;
      }
      .inverse {
        background: #272822;
        color: #777872;
        text-shadow: 0 0 20px #333;
      }
      .inverse h1, .inverse h2 {
        color: #f3f3f3;
        line-height: 0.8em;
      }

      /* Slide-specific styling */
      #slide-inverse .footnote {
        bottom: 12px;
        left: 20px;
      }
      #slide-how .slides {
        font-size: 0.9em;
        position: absolute;
        top:  151px;
        right: 140px;
      }
      #slide-how .slides h3 {
        margin-top: 0.2em;
      }
      #slide-how .slides .first, #slide-how .slides .second {
        padding: 1px 20px;
        height: 90px;
        width: 120px;
        -moz-box-shadow: 0 0 10px #777;
        -webkit-box-shadow: 0 0 10px #777;
        box-shadow: 0 0 10px #777;
      }
      #slide-how .slides .first {
        background: #fff;
        position: absolute;
        top: 20%;
        left: 20%;
        z-index: 1;
      }
      #slide-how .slides .second {
        position: relative;
        background: #fff;
        z-index: 0;
      }

      /* Two-column layout */
      .left-column {
        color: #777;
        width: 20%;
        height: 92%;
        float: left;
      }
        .left-column h2:last-of-type, .left-column h3:last-child {
          color: #000;
        }
      .right-column {
        width: 75%;
        float: right;
        padding-top: 1em;
      }
    </style>
  </head>
  <body>
    <textarea id="source">
name: inverse
layout: true
class: center, middle, inverse
---

    </textarea>
    <script src='https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/latest.js?config=TeX-MML-AM_CHTML' async></script>
    <script type="text/x-mathjax-config">
      MathJax.Hub.Config({
        tex2jax: {
          inlineMath: [["$","$"],["\\(","\\)"]]
        }
      });
    </script>
    <script src="https://remarkjs.com/downloads/remark-latest.min.js" type="text/javascript">
    </script>
    <script type="text/javascript">
      var slideshow = remark.create({
        ratio: "16:9",
        navigation: {
          click: true,
        },
        highlightLines: true,
        highlightSpans: true,
        // highlightStyle: "solarized-light",
        });
    </script>
  </body>
</html>
'''